on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository, build the project, run tests, generate a version using semantic release
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "yarn"
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn ci:test
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
